--#11
/*
Show the manager and number of calls received for each hour of the day on 2017-08-12
*/



--#12
/*
80/20 rule. It is said that 80% of the calls are generated by 20% of the callers. 
Is this true? 
What percentage of calls are generated by the most active 20% of callers.
*/



--#13
/* 
Annoying customers. Customers who call in the last five minutes of a shift are annoying. 
Find the most active customer who has never been annoying.
*/



--#14
/*
Maximal usage. 
If every caller registered with a customer makes a call in one day then that customer has "maximal usage" of the service. 
List the maximal customers for 2017-08-13.
*/



--#15
/*
Consecutive calls occur when an operator deals with two callers within 10 minutes.
Find the longest sequence of consecutive calls – 
give the name of the operator and the first and last call date in the sequence.
*/


